pipeline {
  agent any
  stages {
    stage('Escenario de prueba') {
      //parallel {
        stage('Message') {
          steps {
            echo 'Hello'
            //sh '/home/david/Documents/build.sh'
            sh './scripts/build.sh'
          }
        }
        //stage('Buzz Test') {
          //steps {
            //sh '/home/david/Documents/test-all.sh'
          //}
        //}
      //}
    }

  }
}
